### ISSUE TITLE
Espresso tutorial needs an update from tcl to python

### ISSUE THREAD

**Issue by junghans** [votca/csg-tutorials#11]
Bascially the `spce.tcl` in https://github.com/votca/csg-tutorials/tree/master/spce/ibi_espresso needs to be converted to python.

**Comment by junghans** [comment]
@fweik & @RudolfWeeber can you give me some pointers?

**Comment by junghans** [comment]
@mkuron & @KaiSzuttor could you please help to convert https://github.com/votca/csg-tutorials/blob/master/spce/ibi_espresso/spce.tcl to python?

**Comment by fweik** [comment]
I'll have a look. Do you want to keep the TCL script or replace it?

**Comment by fweik** [comment]
Does anybody know why these lines are needed?

```tcl
set f [open "traj.xyz" "w"]
close $f
set f [open "energy.dat" "w"]
close $f
```

**Comment by junghans** [comment]
> I'll have a look. Do you want to keep the TCL script or replace it?

I want to replace it, no need to keep tcl around.

> Does anybody know why these lines are needed?

They seem unused, so just drop them.

**Comment by junghans** [comment]
Detection for espresso: e9727d01acab6fc94e9014a52dc798f0247bb0be
