### ISSUE TITLE
Investigate failing tests

### ISSUE THREAD

**Issue by junghans** [votca/csg-tutorials#59]
Related to #3 and #4 

I had to disable some tests again in #58 

- [x] methanol/imc_gromacs-remd (#62)
- [x] methanol/imc (#61)
- [x] propane/imc (#61)
- [ ] spce/cma/simple (#63)

**Comment by junghans** [comment]
The imc test all seem to fail on the potential crop, which we might be able to remove now (see https://github.com/votca/csg/issues/429).

**Comment by abrukhno** [comment]
> The imc test all seem to fail on the potential crop, which we might be able to remove now (see [votca/csg#429](https://github.com/votca/csg/issues/429)).

Hi, this has been a long standing issue, so indeed cropping should be avoided.
